version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGODB_URL=mongodb+srv://Dhananji:Dhanu123@cluster0.qamgjv7.mongodb.net/salon_db?retryWrites=true&w=majority
    ports:
      - "8070:8070"
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend