version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: Dhananji
      MONGO_INITDB_ROOT_PASSWORD: Dhanu123
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
      
  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/salon_db
    ports:
      - "8070:8070"
    depends_on:
      - mongodb
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
